// Golden files for the printer — two artifacts per source file:
//
//   <file>.collector.txt          what the module becomes, so Vitest collects it
//   <file>__<test>.txt            one per test: the module pruned to what that
//                                 test needs, plus the test. This is both what
//                                 actually runs and what the results view hands
//                                 a user who wants to poke at it locally.
//
// Run with UPDATE_GOLDEN=1 to rewrite them. A golden that does not exist yet is
// written rather than failed, so a fresh clone starts from what it has.
import { test, expect, describe } from "vitest";
import fs from "node:fs";
import path from "node:path";
import { minimalFor } from "../release/vite-plugin/minimal.mts";
import { emitFor, repoRoot, transformFor } from "./helpers.mts";

const files = [
  "examples/slug.ts",
  "examples/counter.ts",
  "examples/users.ts",
  "examples/parser.ts",
  "examples/stats.ts",
  "examples/cart.ts",
  "examples/tokens.ts",
  "scratch/failing.ts",
];

const dir = path.join(import.meta.dirname, "__golden__");
fs.mkdirSync(dir, { recursive: true });

/** One golden file per test: `<file>__<test name>.txt`, kept filesystem-safe. */
const goldenFor = (file: string, name: string) =>
  path.join(
    dir,
    `${file.replace(/[/]/g, "__")}__${name.replace(/[^\w.[\]-]+/g, "_")}.txt`,
  );

const expected = new Set<string>();

describe("printer output", () => {
  for (const file of files) {
    describe(file, () => {
      for (const { name } of emitFor(file).tests) {
        const golden = goldenFor(file, name);
        expected.add(path.basename(golden));
        test(name, () => {
          const rendered = minimalFor(file, name);
          if (process.env.UPDATE_GOLDEN || !fs.existsSync(golden)) fs.writeFileSync(golden, rendered);
          expect(rendered).toBe(fs.readFileSync(golden, "utf8"));
        });
      }
    });
  }

  for (const file of files) {
    test(`${file} — collector`, async () => {
      const golden = path.join(dir, `${file.replace(/[/]/g, "__")}.collector.txt`);
      expected.add(path.basename(golden));
      const { code } = await transformFor(file);
      // only the appended part, with this machine's path taken back out
      const rendered = code
        .slice(code.indexOf("// ───────── generated by"))
        .replaceAll(`${repoRoot}/`, "");
      if (process.env.UPDATE_GOLDEN || !fs.existsSync(golden)) fs.writeFileSync(golden, rendered);
      expect(rendered).toBe(fs.readFileSync(golden, "utf8"));
    });
  }

  test("every golden file belongs to a test that still exists", () => {
    const orphans = fs
      .readdirSync(dir)
      .filter((f) => f.endsWith(".txt") && !expected.has(f));
    if (process.env.UPDATE_GOLDEN)
      for (const f of orphans) fs.unlinkSync(path.join(dir, f));
    else expect(orphans).toEqual([]);
  });

  test("warns about non-values and not-tests with positions", () => {
    const { warnings } = emitFor("scratch/failing.ts");
    expect(warnings).toEqual([
      {
        line: 19,
        column: 4,
        length: 6,
        message: "`number` is a type, not a value",
      },
    ]);
  });
});
