// The preamble of the generated module: the Vitest import, plus whatever the
// printed tests turned out to need (ntCheck, readFileSync, value re-imports of
// type-only bindings, and the nt_unsupported / nt_env helpers).
import { asEmitContext, isInputOrContext } from "./context.mts";

import type { EmitContext, EmitInputOrContext } from "./context.mts";

import type { Expect, Invoke } from "../../dsl.import.meta.vitest.ts";
import type { printHeader } from "../../_internal/harness.mts";
/** All the preamble reads: a whole context, or just these four fields. */
export type HeaderParts = Pick<
  EmitContext,
  "used" | "imports" | "warnings" | "quote" | "runtime"
>;

export function headerLines(
  inputOrContextOrParts: EmitInputOrContext | HeaderParts,
): string[] {
  const cx: HeaderParts = isInputOrContext(inputOrContextOrParts, "program")
    ? asEmitContext(inputOrContextOrParts)
    : inputOrContextOrParts;
  const lines: (string | null)[] = [
    `// ───────── generated by namespace-tests; not part of your build ─────────`,
    `import { test, expect } from "vitest";`,
    cx.used.task ? `import { ntCheck } from ${cx.quote(cx.runtime)};` : null,
    cx.used.fs ? `import { readFileSync } from "node:fs";` : null,
    ...[...cx.imports].flatMap(([spec, names]) => {
      const ns = [...names].filter((n) => n.startsWith("* as "));
      const named = [...names].filter((n) => !n.startsWith("* as "));
      return [
        ...ns.map(
          (n) =>
            `import ${n} from ${cx.quote(spec)}; // value import: the original import is type-only`,
        ),
        named.length
          ? `import { ${named.join(", ")} } from ${cx.quote(spec)}; // value import: the original import is type-only`
          : null,
      ];
    }),
    cx.warnings.length
      ? `const nt_unsupported = (t: string) => { throw new Error(\`namespace-tests: cannot materialize \\\`\${t}\\\`\`); };`
      : null,
    cx.used.env
      ? `const nt_env = (n: string) => { if (process.env[n] === undefined) throw new Error(\`namespace-tests: env var \${n} is not set\`); return process.env[n]!; };`
      : null,
  ];
  return lines.filter((l): l is string => l !== null);
}

declare namespace Tests.headerLines {
  type Plain = `
    declare namespace a {
      export type T = Expect<1, "=", 1>;
    }
  `;
  type ReadsFile = `
    declare namespace a {
      export type T = Expect<FromFile<"./a.txt">, "=", "hi">;
    }
  `;

  /** a generated test module is an ordinary Vitest file */
  export type Always = Expect<
    Invoke<typeof printHeader, [Plain]>,
    "includes",
    'import { test, expect } from "vitest";'
  >;

  /** `FromFile` pulls in the reader it prints */
  export type FileReader = Expect<
    Invoke<typeof printHeader, [ReadsFile]>,
    "includes",
    'import { readFileSync } from "node:fs";'
  >;

  /** a file with nothing to run has no preamble either */
  export type Empty = Expect<
    Invoke<typeof printHeader, ["const add = (a: number) => a;"]>,
    "=",
    []
  >;
}
