// What Vitest is actually given for a file with namespace tests: the file, then
// a block that pulls in one generated module per test. The plugin appends this
// during `transform`; `nt-minimal --collector` prints the same thing, so what
// the editor shows you is what runs.
import path from "node:path";

import type { Expect, Invoke, Table } from "../dsl.import.meta.vitest.ts";

/** The suffix every generated test module carries. */
export const SUFFIX = ".namespace.test.ts";

/** A filesystem-safe id for one test, beside the module it came from. */
export const idFor = (source: string, name: string) =>
  path.join(
    path.dirname(source),
    `${path.basename(source).replace(/\.[cm]?tsx?$/, "")}.${name.replace(/[^\w[\]-]+/g, "_")}${SUFFIX}`,
  );

/** One line of the collector, anchored to the `export type` it runs. */
export type CollectorLine = { code: string; line: number | null };

/**
 * The block appended to a module with tests. `import.meta.vitest` is Vitest's
 * own answer to "is this the file being collected", so a module that is merely
 * imported by something else adds nothing.
 */
export const collectorLines = (
  imports: { id: string; line: number }[],
): CollectorLine[] => [
  { code: ``, line: null },
  {
    code: `// ───────── generated by namespace-tests; not part of your build ─────────`,
    line: null,
  },
  { code: `if (import.meta.vitest) {`, line: null },
  ...imports.map(({ id, line }) => ({
    code: `  await import(${JSON.stringify(id)});`,
    line,
  })),
  { code: `}`, line: null },
  { code: ``, line: null },
];

/** The module Vitest sees: the source, then the collector. */
export const collected = (code: string, collector: CollectorLine[]) =>
  `${code}\n${collector.map((l) => l.code).join("\n")}`;

declare namespace idFor {
  /** beside the module, named for the module and the test */
  export type Names = Table<
    typeof idFor,
    [
      [
        args: ["src/counter.ts", "Counter > Chainable"],
        expected: "src/counter.Counter_Chainable.namespace.test.ts",
      ],
      [
        args: ["src/codec.mts", "encode > Tagged[1]"],
        expected: "src/codec.encode_Tagged[1].namespace.test.ts",
      ],
    ]
  >;
}

declare namespace collectorLines {
  type Block = Invoke<
    typeof collectorLines,
    [[{ id: "./a.namespace.test.ts"; line: 3 }]]
  >;

  /** the import is anchored to the line the test was written on */
  export type Anchored = Expect<
    Block,
    "matches",
    [
      { code: "" },
      { line: null },
      { code: "if (import.meta.vitest) {" },
      { code: '  await import("./a.namespace.test.ts");'; line: 3 },
      { code: "}" },
      { code: "" }
    ]
  >;
}
